### DISCUSSION TITLE
How to describe a simple array in config file

### DISCUSSION THREAD

**Discussion by frntn** [tinacms/tinacms#3544] [Help]
I'm using tina on a hugo website.
My content files are in markdown
And I want to generate a frontmatter like this one : 

```yaml
---
date: 2021-12-02
title: "Sample Title"
description : "this is my description"
watch: cbd02198-503e-47e4-9c50-c428eb80eef5
featured: true
images: 
  - "images/events/2021-12-02/concert.jpg"
  - "images/events/2021-12-02/poster.jpg"
---
```

So I tried this simple config 

```typescript
  schema: {
    collections: [
      {
        label: "Events",
        name: "events",
        path: "content/events",
        format: 'md',
        fields: [
          {
            label: "Image Gallery",
            name: "gallery",
            type: "object",
            list: true,
            fields: [
              { 
                label: "Image", 
                name: "image", 
                type: "image" 
              },
            ],
          },
          { name: "date", label: "date", type: "datetime",},
          { name: "title", label: "title", type: "string",},
          { name: "description", label: "description", type: "string",},
          { name: "watch", label: "Peertube video ID", type: "string",},
          { name: "featured", label: "Display on Homepage ?", type: "boolean",},
          { name: "body", label: "Body of Document", type: "rich-text", description: "This is the markdown body", isBody: true,},
        ],
      },
```

But when trying to add an image using tina I get the followin error message (#2113) :  
> "Cannot navigate away from an invalid form" 

Same error when trying to copy/paste the sample from the documentation [Custom List Rendering](https://tina.io/docs/extending-tina/customize-list-ui/)

I believe this is a dumb question with very trivial answer, but I couldn't find the answer....
