### DISCUSSION TITLE
Support for Hugo i18n translation files or a top level list?

### DISCUSSION THREAD

**Discussion by major-mayer** [tinacms/tinacms#4197] [Help]
I recently tried to migrate my Hugo Website from Forestry to TinaCMS and have a few problems.
One of it is that the document sections is still not supported as it was in Forestry: https://github.com/tinacms/tinacms/issues/1982

I especially need it for the translation files of which I have a few of.
They are looking like this:
```yaml
---
- id: nav_button
  translation: Kontakt
- id: service_subtitle
  translation: Entdecken Sie
- id: service_title
  translation: Unsere Angebote
```

I tried manually creating a schema, but as this is a top-level list and you can not specify fields of type list, i found no way how to create a schema.

I tried adding a "translations" object on the top level and putting the list below as a workaround:
```ts
fields: [
          {
            type: "object",
            name: "translations",
            label: "Übersetzung",
            list: true,
            fields: [
            {
              type : "string",
              name : "id",
              label  :"ID"
            },
             {
              type : "string",
              name : "translation",
              label : "Translation"
             }
            ],
          },
        ],
```

But when I add "translations" as the top-level object, Hugo's i18n tooling cannot find the translations anymore.
Any idea how to solve this problem?
