### DISCUSSION TITLE
Save Draft and then Publish Changes

### DISCUSSION THREAD

**Discussion by stvee4637** [tinacms/tinacms#4621] [Ideas]
Hi, Thank you, guys, for this package it is really helpful, something I noticed is when you save any changes in production it will make an individual commit and that will cause the site to redeploy, when our designers are making lots of small changes I get blocked by Vercel for too many deployments and have to wait 30 mins and then manually redeploy. Is it possible to have the save buttons save to a draft instead (on the client locally or as a different branch on GitHub) and then let the user publish those changes all at once? Please let me know if something like this could work

**Comment by cascading-jox** [comment]
I would also like to have this functionality. Adding this to my github action kind of works. It cancels any previous deployments. 

```YML
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 ```
