### ISSUE TITLE
Allowed passing custom class to wrapper

### ISSUE THREAD

**Issue by wenerme** [tinacms/tinacms#1101]
## Summary

Need to customize the wrapper element, have to use global style trick.

```scss
  // tinacms used to use TinaReset class, now changed to SiteWrapper
  // have to use prefix match to select the wrapper element
  div[class^="TinaReset"],div[class^="SiteWrapper"]{
    // full screeen height
    height: 100%;
    // hide built in toggle 
    button[class^="SidebarToggleButton"]{
      display: none;
    }
  }
```

### Motivation

change the wrapper element style
