### ISSUE TITLE
feat: array/groups with predefined objects

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#202]
Via @thomkrupa:

I'd like to be able to do something like:

```
components: 
    - name: Section // component tag, eg. <Section>
      header: 
      - name: Subheading
        text: Hello this is subheading
        variant: accent
      - name: Heading
        text: main heading
      body:
      - columns: 2
      - components: 
        - name: Image
          src: 'path/to/image'
        - name: Content
          text: 'Lorem ipsum dolor sit'
```

It would be awesome to have an option to predefine what can be in components.
The UI would be “Add new component” with a list of possible components.
