### ISSUE TITLE
Tina overwrites Front Matter Fields that are not in the form template

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#216]
Page frontmatter:
```
---
title: Super Vacation Land
template: HomePage
slug: ''
featuredImage: images/island.jpg
subtitle: ' Welcome to paradise '
meta:
  description: This is a meta description.
  title: The Ultimate Gatsby Starter
gallery:
  - alt: yellow rope image
    image: /images/gallery1.jpg
    title: Yellow Rope
  - alt: umbrellas
    image: ../../static/images/gallery2.jpg
    title: a bunch of umbrellas
  - alt: yellow ice cream
    image: ../../static/images/gallery3.jpg
    title: Yellow Ice Cream
---
```

Form Template
```
let HomeForm = {
  fields: [
    {
      label: 'Title',
      name: 'rawFrontmatter.title',
      component: 'text',
    },
    {
      label: 'Title',
      name: 'rawFrontmatter.subtitle',
      description: 'Subtitle',
      component: 'text',
    },
  ],
}```
