### ISSUE TITLE
Add "Group" Field 

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#30]
Some data is organized into objects. We want to provide a UI for rendering the data in those objects grouped together. 

Here's an example of some data:

```yaml
title: Hello World
author:
  firstName: Billy
  lastName: Joel
```

The field definition might look something like

```javascript
let fields = [
  { name: "title", label: "Author", component: "text" },
  {
    name: "author",
    label: "Author",
    component: "group",
    fields: [
      { name: "firstName", component: "text" },
      { name: "lastName", component: "text" },
    ]
]
```
