### ISSUE TITLE
content markdown seems to be formatted incorrectly after Hugo site conversion from Forestry to Tina

### ISSUE THREAD

**Issue by padders** [tinacms/tinacms#3886]
### Discussed in https://github.com/tinacms/tinacms/discussions/3885

<div type='discussions-op-text'>

<sup>Originally posted by **padders** May  1, 2023</sup>
Hi guys, 

I've run through a conversion to Tina of a Hugo site running on Forestry following the guide and video. The site seems to be up and running ok after a few tweeks. However the pages don't load into the editor correctly and it looks like the markdown format on my old site is vastly different to the ones Tina generates. This is an example of what Tina creates

```
---
page_section:
  - title: Title
    content: Content test
    add_image: true
    floating_image: /images/android-chrome-192x192.png
    image_side: true
    large_paragraph_text: true
    template: basic-content
title: Test
---
```

Whereas the old site looks like this (I've only added a small amount of the content)

```
---
_template: page_template
---

+++
meta_description = "Live Dates - blah blah"
meta_og_image = "/uploads/group-slim.jpg"
title = "Live Dates | blah blah"
[menu.nav]
name = "Live Dates"
url = "/tour"
weight = 4
[[page_section]]
banner_image = "/uploads/0ct-2019-copy.jpg"
darken_background_image = true
hero_button_text = "Explore Us"
hero_button_url = "#"
hero_text_content = ""
hero_title = "Live Dates"
link_btn = false
template = "hero-partial"
thin_hero = true
[[page_section]]
all_gigs_url = "/tour"
band_filter = ""
display_limit = 10000
section_title = "Upcoming Dates"
template = "upcoming_gigs"
```

Does anyone know if there's an automatic method of converting these, or am I going to have to go through them manually?</div>
