### ISSUE TITLE
Certain emojis saved as unicode and cause rich text field to save as a single line in .mdx file

### ISSUE THREAD

**Issue by blanchardjeremy** [tinacms/tinacms#5331]
## What I'm doing: 
I'm adding the emoji 🔨  to a rich text body inside a field within my `.mdx` file.

## Expected result: 

```
---
title: Security Essentials
excerpt: ''
author: ''
sections:
  - title: Essential
    checklistItems:
      - title: Use a password manager with strong passwords
        body: |
          Test Test

          🔨  Multiline support present

          * One
          * Two 
          * Three
        id: password-manager
---

Body here
```

## Current result: 
When I add the 🔨  emoji, it gets saved as `\U0001F528` and the whole thing gets forced into a one-line string. My actual body text is MUCH longer than this, and having it one line is not usable.

```
---
title: Security Essentials
excerpt: ''
author: ''
sections:
  - title: Essential
    checklistItems:
      - title: Use a password manager with strong passwords
        body: "Test Test\n\n\U0001F528 Multiline support present\n\n* One\n* Two \n* Three\n"
        id: password-manager
---

Body here
```

## Notes

* A couple of other emojis I added work just fine (they keep multi-line support

### Reproduction

N/A

### Steps to reproduce

Just add the 🔨  to an existing multi-line rich text field 

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 117.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 131.1.73.89
  npmPackages:
    @tinacms/cli: ^1.6.12 => 1.6.12 
    tinacms: ^2.4.0 => 2.5.0
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.
